In [1]:
import os
os.chdir('/data/l989o/deployed/a')
import sys
if '/data/l989o/a' in sys.path:
    sys.path.remove('/data/l989o/a')

In [2]:
import scanpy as sc
import anndata as ad
import numpy as np
import matplotlib.pyplot as plt
import os
import h5py
import pickle
import pandas as pd
from data import file_path
from tqdm.notebook import tqdm

from metadata import get_metadata

True
<KeysViewHDF5 ['count', 'maximum', 'mean', 'sum', 'variance']>

In [3]:
df = get_metadata()

discarding 153 omes from the Basel cohort, remaining: 223
discarding 153 omes from the Zurich cohort, remaning: 229
clearing metadata
warning: df_basel[Subtype] contains 5 NAs out of 223 values
warning: df_basel[clinical_type] contains 5 NAs out of 223 values
warning: df_zurich[clinical_type] contains 34 NAs out of 229 values
flattening PTNM_T labels
warning: interpreting the PTNM_T label "[]" as "TX"
flattening PTNM_N labels
warning: interpreting the PTNM_N label "[]" as "pNX"
warning: interpreting the PTNM_N labels "0sl" and "0sn" as "pN0"
warning: interpreting the "M0_IPLUS" label as "cMo(i+)"
metadata cleaned

In [4]:
df

,FileName_FullStack,merged_pid,diseasestatus,PrimarySite,Subtype,clinical_type,Height_FullStack,Width_FullStack,area,sum_area_cells,Count_Cells,PTNM_T,PTNM_N,PTNM_M,DFSmonth,OSmonth,images_per_patient,images_per_patient_filtered,cohort
2,BaselTMA_SP41_15.475kx12.665ky_10000x8500_5_20...,166,tumor,breast,PR-ER-,TripleNeg,723,749,541527,356411,3068,T2,pN0,M0,35.0,37.0,1,1,basel
3,BaselTMA_SP41_25.475kx12.665ky_8000x8500_3_201...,238,tumor,breast,PR+ER+,HR+HER2-,840,712,598080,286198,3173,T1,pN2,M0,140.0,233.0,2,2,basel
4,BaselTMA_SP41_25.475kx12.665ky_8000x8500_3_201...,238,non-tumor,breast,PR+ER+,HR+HER2-,765,689,527085,193119,2121,T1,pN2,M0,140.0,233.0,2,2,basel
6,BaselTMA_SP41_25.475kx12.665ky_8000x8500_3_201...,68,tumor,breast,PR+ER+,HR+HER2-,689,688,474032,218846,2262,T1,pN2,M0,169.0,169.0,2,1,basel
7,BaselTMA_SP41_15.475kx12.665ky_10000x8500_5_20...,72,tumor,breast,PR-ER+,HR+HER2-,716,737,527692,289717,2740,T1,pN0,pM1,186.0,186.0,2,1,basel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,ZTMA208_slide_13.25kx14.95ky_7000x7000_8_20171...,308,tumor,breast,PR+ER+,NaN,492,514,252888,243839,3674,TX,pNX,pM1,NaN,NaN,6,4,zurich
354,ZTMA208_slide_28.23kx22.4ky_7000x7000_5_201711...,301,tumor,breast,PR+ER+,NaN,503,475,238925,98597,1256,T3,pN1,pM1,NaN,NaN,6,4,zurich
355,ZTMA208_slide_28.23kx22.4ky_7000x7000_5_201711...,301,tumor,breast,PR+ER+,NaN,450,541,243450,102638,1227,T3,pN1,pM1,NaN,NaN,6,4,zurich
356,ZTMA208_slide_28.23kx22.4ky_7000x7000_5_201711...,301,tumor,breast,PR+ER+,NaN,464,519,240816,123359,1580,T3,pN1,pM1,NaN,NaN,6,4,zurich
357,ZTMA208_slide_20.73kx15.16ky_7000x7000_6_20171...,301,tumor,breast,PR+ER+,NaN,488,540,263520,241444,3418,T3,pN1,pM1,NaN,NaN,6,4,zurich